---
steps:
  - name: building-topaz
    image: harbor.crystalnet.org/library/kernel_builder_droid:latest
    pull: true
    environment:
      DEVICE: psyche
      KBUILD_BUILD_USER: cronix
      KBUILD_BUILD_HOST: Supermicro
    commands:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      - /usr/local/bin/kernel_builder.sh
