---
steps:
  - name: building-topaz
    image: harbor.crystalnet.org/library/kernel_builder_droid:latest
    pull: true
    environment:
      CROSS_COMPILE: aarch64-linux-gnu-
      CROSS_COMPILE_COMPAT: arm-linux-gnueabi-
      LLVM: "1"
      LLVM_IAS: "1"
      DEVICE: psyche
      KBUILD_BUILD_USER: cronix
      KBUILD_BUILD_HOST: Supermicro
    commands:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      - make O=out CC=clang ARCH=arm64 psyche_defconfig
      - scripts/config
        --set-str CONFIG_LOCALVERSION "-TopazKSU"
        --enable CONFIG_KPROBES
        --enable CONFIG_HAVE_KPROBES
        --enable CONFIG_KPROBE_EVENTS