---
steps:
  - name: building-topaz
    image: harbor.crystalnet.org/library/kernel_builder_droid:latest
    pull: true
    environment:
      CROSS_COMPILE: aarch64-linux-gnu-
      CROSS_COMPILE_COMPAT: arm-linux-gnueabi-
      CLANG_WARN_STRICT_PROTOTYPES: "no"
      LLVM: "1"
      LLVM_IAS: "1"
      DEVICE: psyche
      KBUILD_BUILD_USER: cronix
      KBUILD_BUILD_HOST: Supermicro
    commands:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      - make O=out CC=clang ARCH=arm64 psyche_defconfig
      - scripts/config
        --file out/.config
        --set-str CONFIG_LOCALVERSION "-TopazKSU"
        --enable CONFIG_KPROBES
        --enable CONFIG_HAVE_KPROBES
        --enable CONFIG_KPROBE_EVENTS
      - make ARCH=arm64
          O=out
          CC=clang
          AR=llvm-ar
          NM=llvm-nm
          OBJCOPY=llvm-objcopy
          OBJDUMP=llvm-objdump
          STRIP=llvm-strip
          -j"$(nproc --all)" | tee log.txt	