---
steps:
  - name: building-topaz
    image: harbor.crystalnet.org/library/kernel_builder_droid:latest
    environment:
      DEVICE: psyche
      KBUILD_BUILD_USER: cronix
      KBUILD_BUILD_HOST: Supermicro
    commands:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      - git clone https://github.com/psych0d0g/woodpecker-scripts.git --depth=1 -b kona script && cd script
      - ./build-kernel
